[package]
name = "shinnku-com-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
anyhow = "1"
color-eyre = "0.6"
